---
title: "Testrun3"
author: "Luke Finn & Sean Tynan"
date: "2/14/2022"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,include=FALSE}
library(tidyverse)
library(ggplot2)
library(stargazer)
library(dplyr)
heartfaildata=read.csv(file=file.choose())
```

```{r}
agesex1=heartfaildata%>%select(time,DEATH_EVENT,sex,age)
agesex1=agesex1%>%mutate(time_cat=cut(time,breaks=c(0,10,30,60,100,285)))%>%na.omit()
agesex1=agesex1%>%mutate(age_cat=cut(age,breaks=c(39,50,60,70,80,95)))%>%na.omit()
agesex1=agesex1%>%relocate(time_cat,time)
agesex1.tbl <-agesex1 %>% group_by(time_cat,age_cat, sex, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
agesex1.tbl<-agesex1.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))

agesex.glm=glm(formula=cbind(`0` , `1`)~ age_cat+sex+factor(time_cat),family=binomial(link="logit"),data=agesex1.tbl)
summary(agesex.glm)
```



```{r}
Model1 <- glm(DEATH_EVENT ~ age+anaemia+creatinine_phosphokinase+diabetes+ejection_fraction+high_blood_pressure+platelets+serum_creatinine+serum_sodium+sex+smoking+time, data =heartfaildata)
summary(Model1)
```



```{r}
agediab1=heartfaildata%>%select(time,DEATH_EVENT,diabetes,age,anaemia,high_blood_pressure,smoking)
agediab1=agediab1%>%mutate(time_cat=cut(time,breaks=c(0,10,30,60,100,285)))%>%na.omit()
agediab1=agediab1%>%mutate(age_cat=cut(age,breaks=c(39,50,60,70,80,95)))%>%na.omit()
agediab1=agediab1%>%relocate(time_cat,time)
agediab1.tbl <-agediab1 %>% group_by(time_cat,age_cat, diabetes,anaemia,smoking,high_blood_pressure, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
#agediab1.tbl <-agediab1 %>% group_by(time_cat,age_cat, diabetes,anaemia, DEATH_EVENT, .drop = F) %>%
  #tally() %>% spread(anaemia, n, replace_na(0))%>%
  #mutate(NotAnmic = `0`, Anmic= `1`)
#agediab1.tbl<-agediab1.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
#agediab1.tbl <-agediab1 %>% group_by(time_cat,age_cat, diabetes,anaemia, DEATH_EVENT, .drop = F) %>%
#  tally() %>% spread(diabetes, n, replace_na(0))%>%
 # mutate(Notdiabic = `0`, diabic= `1`)
#agediab1.tbl <-agediab1 %>% group_by(time_cat,age_cat, diabetes,anaemia,high_blood_pressure, DEATH_EVENT, .drop = F) %>%
  #tally() %>% spread(high_blood_pressure, n, replace_na(0))%>%
  #mutate(NoHBP = `0`, HBP= `1`)
agediab1.tbl <-agediab1 %>% group_by(time_cat,age_cat, diabetes,anaemia,high_blood_pressure,smoking, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(smoking, n, replace_na(0))%>%
  mutate(Nosmk = `0`, smk= `1`)
agediab.glm=glm(formula=cbind(`0` , `1`)~ age_cat+smk+Nosmk+factor(time_cat),family=binomial(link="logit"),data=agediab1.tbl)
summary(agediab.glm)
```



```{r}
Final1=heartfaildata%>%select(time,DEATH_EVENT,creatinine_phosphokinase,serum_creatinine,serum_sodium)
Final1=Final1%>%mutate(time_cat=cut(time,breaks=c(0,10,30,60,100,285)))%>%na.omit()
Final1=Final1%>%mutate(sersod_cat=cut(serum_sodium,breaks=c(110,135,145,150),dig.lab=7))%>%na.omit()
Final1=Final1%>%mutate(sercre_cat=cut(serum_creatinine,breaks=c(0.49,1.3,2,9.5)))%>%na.omit()
Final1=Final1%>%mutate(crepho_cat=cut(creatinine_phosphokinase,breaks=c(10,120,500,1000,8000),dig.lab=7))%>%na.omit()
Final1=Final1%>%relocate(time_cat,time)
Final1.tbl <-Final1 %>% group_by(time_cat,sersod_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
Final1.tbl<-Final1.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
TableFinal1=Final1.tbl%>%select("time_cat", "sersod_cat",                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1","Total","DeathProb")
 
Final2.tbl <-Final1 %>% group_by(time_cat,sercre_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
Final2.tbl<-Final2.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
TableFinal2=Final2.tbl%>%select("time_cat", "sercre_cat",                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1","Total","DeathProb")

Final3.tbl <-Final1 %>% group_by(time_cat,crepho_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
Final3.tbl<-Final3.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
TableFinal3=Final3.tbl%>%select("time_cat", "crepho_cat",                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1","Total","DeathProb")
merged.table <-Reduce(function(...) merge(..., all = TRUE),
       list(TableFinal1, TableFinal2, TableFinal3))


Final.glm=glm(formula=
                cbind(DEATH_EVENT_No, DEATH_EVENT_Yes)~ factor(time_cat),family=binomial(link = "logit"),data=merged.table)
summary(Final.glm)
```


```{r}
par(mfrow=c(2,2))
plot(Final.glm)
```




```{r}
merged.table %>% print(n = Inf)
```


```{r}
par(mfrow=c(2,2))
plot(Final.glm)
```



```{r}
glmnull=heartfaildata%>%select(DEATH_EVENT)
#glmnull=glmnull%>%mutate(time_cat=cut(time,breaks=c(0,10,30,60,100,285)))%>%na.omit()
#glmnull=glmnull%>%mutate(age_cat=cut(age,breaks=c(39,50,60,70,80,95)))%>%na.omit()
#agesex1=agesex1%>%relocate(time_cat,time)
glmnull.tbl <-glmnull %>% group_by(DEATH_EVENT, .drop = F)# %>%
#  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
#  mutate(Total = `0` + `1`)
#agesex1.tbl<-agesex1.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))

null.glm=glm(formula=DEATH_EVENT~ 1,family=binomial(link="logit"),data=glmnull.tbl)
summary(null.glm)
```


```{r}
par(mfrow=c(2,2))
plot(Final.glm)
```



```{r}
glm1=heartfaildata%>%select(DEATH_EVENT,time)
glm1=glm1%>%mutate(time_cat=cut(time,breaks=c(0,10,30,60,100,285)))%>%na.omit()

glm1=glm1%>%relocate(time_cat,time)
glm1.tbl <-glm1 %>% group_by(time_cat, DEATH_EVENT, .drop = F)# %>%
#  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
#  mutate(Total = `0` + `1`)
#agesex1.tbl<-agesex1.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))

first.glm=glm(formula=DEATH_EVENT~ factor(time_cat),family=binomial(link="logit"),data=glm1.tbl)
summary(first.glm)
```


```{r}
glm2=heartfaildata%>%select(DEATH_EVENT,time,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking)
glm2=glm2%>%mutate(time_cat=cut(time,breaks=c(0,10,30,60,100,285)))%>%na.omit()

glm2=glm2%>%relocate(time_cat,time)
glm2.tbl <-glm2 %>% group_by(time_cat, DEATH_EVENT,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking, .drop = F)# %>%
#  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
#  mutate(Total = `0` + `1`)
#agesex1.tbl<-agesex1.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))

second.glm=glm(formula=DEATH_EVENT~age+anaemia+creatinine_phosphokinase+diabetes+ejection_fraction+high_blood_pressure+platelets+serum_creatinine+serum_sodium+sex+smoking +factor(time_cat),family=binomial(link="logit"),data=glm2.tbl)
summary(second.glm)
```



```{r}
glm3=heartfaildata%>%select(DEATH_EVENT,time,creatinine_phosphokinase,serum_creatinine,serum_sodium)
glm3=glm3%>%mutate(time_cat=cut(time,breaks=c(0,10,30,60,100,285)))%>%na.omit()
glm3=glm3%>%mutate(sersod_cat=cut(serum_sodium,breaks=c(110,135,145,150),dig.lab=7))%>%na.omit()
glm3=glm3%>%mutate(sercre_cat=cut(serum_creatinine,breaks=c(0.49,1.3,2,9.5)))%>%na.omit()
glm3=glm3%>%mutate(crepho_cat=cut(creatinine_phosphokinase,breaks=c(10,120,500,1000,8000),dig.lab=7))%>%na.omit()
glm3=glm3%>%relocate(time_cat,time)
glm3.tbl <-glm3 %>% group_by(time_cat, DEATH_EVENT,sersod_cat,sercre_cat,crepho_cat, .drop = F)# %>%
#  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
#  mutate(Total = `0` + `1`)
#agesex1.tbl<-agesex1.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))

third.glm=glm(formula=DEATH_EVENT~sersod_cat+sercre_cat+crepho_cat+factor(time_cat),family=binomial(link="logit"),data=glm3.tbl)
summary(third.glm)
```


```{r}
Final1=heartfaildata%>%select(time,DEATH_EVENT,creatinine_phosphokinase,serum_creatinine,serum_sodium)
Final1=Final1%>%mutate(time_cat=cut(time,breaks=c(0,10,30,60,100,285)))%>%na.omit()
Final1=Final1%>%mutate(sersod_cat=cut(serum_sodium,breaks=c(110,135,145,150),dig.lab=7))%>%na.omit()
Final1=Final1%>%mutate(sercre_cat=cut(serum_creatinine,breaks=c(0.49,1.3,2,9.5)))%>%na.omit()
Final1=Final1%>%mutate(crepho_cat=cut(creatinine_phosphokinase,breaks=c(10,120,500,1000,8000),dig.lab=7))%>%na.omit()
Final1=Final1%>%relocate(time_cat,time)
Final1.tbl <-Final1 %>% group_by(time_cat,sersod_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
Final1.tbl<-Final1.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
TableFinal1=Final1.tbl%>%select("time_cat", "sersod_cat",                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1","Total","DeathProb")
 
Final2.tbl <-Final1 %>% group_by(time_cat,sercre_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
Final2.tbl<-Final2.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
TableFinal2=Final2.tbl%>%select("time_cat", "sercre_cat",                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1","Total","DeathProb")

Final3.tbl <-Final1 %>% group_by(time_cat,crepho_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
Final3.tbl<-Final3.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
TableFinal3=Final3.tbl%>%select("time_cat", "crepho_cat",                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1","Total","DeathProb")
merged.table <-Reduce(function(...) merge(..., all = TRUE),
       list(TableFinal1, TableFinal2, TableFinal3))


Final.glm=glm(formula=
                cbind(DEATH_EVENT_No, DEATH_EVENT_Yes)~ factor(time_cat),family=binomial(link = "logit"),data=merged.table)
summary(Final.glm)
```








