---
title: "Testrun1"
author: "Luke Finn & Sean Tynan"
date: "1/31/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
library(tidyverse)
library(ggplot2)
library(stargazer)
heartfaildata=read.csv(file=file.choose())
```

This is using sex as the X variable.

```{r}
heart_1=heartfaildata%>%select(time,DEATH_EVENT,sex)
heart_1=heart_1%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
heart_1=heart_1%>%relocate(time_cat,time)
heart_1.tbl <- heart_1 %>% group_by(time_cat, sex, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
heart_1.tbl<-heart_1.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
heart_1.tbl$sex[heart_1.tbl$sex == 0] <- "female"
heart_1.tbl$sex[heart_1.tbl$sex == 1] <- "male"
```

```{r,include=FALSE}
stargazer(heart_1.tbl, summary = F, rownames = F)
```

```{r}
Table_1=heart_1.tbl%>%select("time_cat", "sex", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Table_1 %>% print(n = Inf)


```

```{r}
ggplot(data = Table_1) + geom_bar(aes(x = sex, y = DeathProb,fill=sex),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```


```{r}
heartf=heartfaildata%>%select(time,DEATH_EVENT,sex,age)
heartf=heartf%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
heartf=heartf%>%mutate(age_cat=cut(age,breaks=c(40,50,60,70,80,90,95)))%>%na.omit()
heartf=heartf%>%relocate(time_cat,time)
heartf.tbl <- heartf %>% group_by(time_cat, sex, age_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
heartf.tbl<-heartf.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
heartf.tbl$sex[heartf.tbl$sex == 0] <- "female"
heartf.tbl$sex[heartf.tbl$sex == 1] <- "male"

```

```{r,include=FALSE}
stargazer(heartf.tbl, summary = F, rownames = F)
```

```{r}
Table1 = heartf.tbl %>% select("time_cat", "sex", "age_cat", 
                                "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Table1 %>% print(n = Inf)

```

```{r}
ggplot(data = Table1) + geom_bar(aes(x = sex, y = DeathProb ,
                                     fill = factor(age_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```



```{r}
heartfcreatphos=heartfaildata%>%select(time,DEATH_EVENT,sex,creatinine_phosphokinase)
heartfcreatphos=heartfcreatphos%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
heartfcreatphos=heartfcreatphos%>%mutate(crepho_cat=cut(creatinine_phosphokinase,breaks=c(10,120,500,1000,8000),dig.lab=5))%>%na.omit()
heartfcreatphos=heartfcreatphos%>%relocate(time_cat,time)
heartfcreatphos.tbl <- heartfcreatphos %>% group_by(time_cat, sex, crepho_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
heartfcreatphos.tbl<-heartfcreatphos.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
heartfcreatphos.tbl$sex[heartfcreatphos.tbl$sex == 0] <- "female"
heartfcreatphos.tbl$sex[heartfcreatphos.tbl$sex == 1] <- "male"
```

```{r,include=FALSE}
stargazer(heartfcreatphos.tbl, summary = F, rownames = F)
```

```{r}
Tablecrepho=heartfcreatphos.tbl%>%select("time_cat", "sex", "crepho_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tablecrepho %>% print(n = Inf)


```

```{r}
ggplot(data = Tablecrepho) + geom_bar(aes(x = sex, y = DeathProb ,
                                     fill = factor(crepho_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
heartfejectfrac=heartfaildata%>%select(time,DEATH_EVENT,sex,ejection_fraction)
heartfejectfrac=heartfejectfrac%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
heartfejectfrac=heartfejectfrac%>%mutate(ejectfrac_cat=cut(ejection_fraction,breaks=c(14,35,40,55,80),dig.lab=5))%>%na.omit()
heartfejectfrac=heartfejectfrac%>%relocate(time_cat,time)
heartfejectfrac.tbl <- heartfejectfrac %>% group_by(time_cat, sex, ejectfrac_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
heartfejectfrac.tbl<-heartfejectfrac.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
heartfejectfrac.tbl$sex[heartfejectfrac.tbl$sex == 0] <- "female"
heartfejectfrac.tbl$sex[heartfejectfrac.tbl$sex == 1] <- "male"
```

```{r,include=FALSE}
stargazer(heartfejectfrac.tbl, summary = F, rownames = F)
```

```{r}
Tableejefra=heartfejectfrac.tbl%>%select("time_cat", "sex", "ejectfrac_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableejefra %>% print(n = Inf)


```

```{r}
ggplot(data = Tableejefra) + geom_bar(aes(x = sex, y = DeathProb ,
                                     fill = factor(ejectfrac_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
heartfplate=heartfaildata%>%select(time,DEATH_EVENT,sex,platelets)
heartfplate=heartfplate%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
heartfplate=heartfplate%>%mutate(plate_cat=cut(platelets,breaks=c(10000,150000,450000,850000),dig.lab=7))%>%na.omit()
heartfplate=heartfplate%>%relocate(time_cat,time)
heartfplate.tbl <- heartfplate %>% group_by(time_cat, sex, plate_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
heartfplate.tbl<-heartfplate.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
heartfplate.tbl$sex[heartfplate.tbl$sex == 0] <- "female"
heartfplate.tbl$sex[heartfplate.tbl$sex == 1] <- "male"
```

```{r,include=FALSE}
stargazer(heartfplate.tbl, summary = F, rownames = F)
```

```{r}
Tableplate=heartfplate.tbl%>%select("time_cat", "sex", "plate_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableplate %>% print(n = Inf)


```

```{r}
ggplot(data = Tableplate) + geom_bar(aes(x = sex, y = DeathProb ,
                                     fill = factor(plate_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
heartfsercre=heartfaildata%>%select(time,DEATH_EVENT,sex,serum_creatinine)
heartfsercre=heartfsercre%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
heartfsercre=heartfsercre%>%mutate(sercre_cat=cut(serum_creatinine,breaks=c(0.5,1.3,2,9.5),dig.lab=7))%>%na.omit()
heartfsercre=heartfsercre%>%relocate(time_cat,time)
heartfsercre.tbl <- heartfsercre %>% group_by(time_cat, sex, sercre_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
heartfsercre.tbl<-heartfsercre.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
heartfsercre.tbl$sex[heartfsercre.tbl$sex == 0] <- "female"
heartfsercre.tbl$sex[heartfsercre.tbl$sex == 1] <- "male"
```

```{r,include=FALSE}
stargazer(heartfsercre.tbl, summary = F, rownames = F)
```

```{r}
Tablesercre=heartfsercre.tbl%>%select("time_cat", "sex", "sercre_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tablesercre %>% print(n = Inf)


```

```{r}
ggplot(data = Tablesercre) + geom_bar(aes(x = sex, y = DeathProb ,
                                     fill = factor(sercre_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```


```{r}
heartfsersod=heartfaildata%>%select(time,DEATH_EVENT,sex,serum_sodium)
heartfsersod=heartfsersod%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
heartfsersod=heartfsersod%>%mutate(sersod_cat=cut(serum_sodium,breaks=c(110,135,145,150),dig.lab=7))%>%na.omit()
heartfsersod=heartfsersod%>%relocate(time_cat,time)
heartfsersod.tbl <- heartfsersod %>% group_by(time_cat, sex, sersod_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
heartfsersod.tbl<-heartfsersod.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
heartfsersod.tbl$sex[heartfsersod.tbl$sex == 0] <- "female"
heartfsersod.tbl$sex[heartfsersod.tbl$sex == 1] <- "male"
```

```{r,include=FALSE}
stargazer(heartfsersod.tbl, summary = F, rownames = F)
```

```{r}
Tablesersod=heartfsersod.tbl%>%select("time_cat", "sex", "sersod_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tablesersod %>% print(n = Inf)


```

```{r}
ggplot(data = Tablesersod) + geom_bar(aes(x = sex, y = DeathProb ,
                                     fill = factor(sersod_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```
Anaemia is yes (1) or no (0) to the following question: Decrease of red blood cells or hemoglobin?

```{r}
anaemiaf=heartfaildata%>%select(time,DEATH_EVENT,anaemia,age)
anaemiaf=anaemiaf%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiaf=anaemiaf%>%mutate(age_cat=cut(age,breaks=c(40,50,60,70,80,90,95)))%>%na.omit()
anaemiaf=anaemiaf%>%relocate(time_cat,time)
anaemiaf.tbl <- anaemiaf %>% group_by(time_cat, anaemia, age_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiaf.tbl<-anaemiaf.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiaf.tbl$anaemia[anaemiaf.tbl$anaemia == 0] <- "No"
anaemiaf.tbl$anaemia[anaemiaf.tbl$anaemia == 1] <- "Yes"

```

```{r,include=FALSE}
stargazer(anaemiaf.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemia1 = anaemiaf.tbl %>% select("time_cat", "anaemia", "age_cat", 
                                "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemia1 %>% print(n = Inf)

```

```{r}
ggplot(data = Tableanaemia1) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(age_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```



```{r}
anaemiafcreatphos=heartfaildata%>%select(time,DEATH_EVENT,anaemia,creatinine_phosphokinase)
anaemiafcreatphos=anaemiafcreatphos%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafcreatphos=anaemiafcreatphos%>%mutate(crepho_cat=cut(creatinine_phosphokinase,breaks=c(10,120,500,1000,8000),dig.lab=5))%>%na.omit()
anaemiafcreatphos=anaemiafcreatphos%>%relocate(time_cat,time)
anaemiafcreatphos.tbl <- anaemiafcreatphos %>% group_by(time_cat, anaemia, crepho_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafcreatphos.tbl<-anaemiafcreatphos.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafcreatphos.tbl$anaemia[anaemiafcreatphos.tbl$anaemia == 0] <- "No"
anaemiafcreatphos.tbl$anaemia[anaemiafcreatphos.tbl$anaemia == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(anaemiafcreatphos.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiacrepho=anaemiafcreatphos.tbl%>%select("time_cat", "anaemia", "crepho_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiacrepho %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiacrepho) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(crepho_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
anaemiafejectfrac=heartfaildata%>%select(time,DEATH_EVENT,anaemia,ejection_fraction)
anaemiafejectfrac=anaemiafejectfrac%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafejectfrac=anaemiafejectfrac%>%mutate(ejectfrac_cat=cut(ejection_fraction,breaks=c(14,35,40,55,80),dig.lab=5))%>%na.omit()
anaemiafejectfrac=anaemiafejectfrac%>%relocate(time_cat,time)
anaemiafejectfrac.tbl <- anaemiafejectfrac %>% group_by(time_cat, anaemia, ejectfrac_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafejectfrac.tbl<-anaemiafejectfrac.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafejectfrac.tbl$anaemia[anaemiafejectfrac.tbl$anaemia == 0] <- "No"
anaemiafejectfrac.tbl$anaemia[anaemiafejectfrac.tbl$anaemia == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(anaemiafejectfrac.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiaejefra=anaemiafejectfrac.tbl%>%select("time_cat", "anaemia", "ejectfrac_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiaejefra %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiaejefra) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(ejectfrac_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
anaemiafplate=heartfaildata%>%select(time,DEATH_EVENT,anaemia,platelets)
anaemiafplate=anaemiafplate%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafplate=anaemiafplate%>%mutate(plate_cat=cut(platelets,breaks=c(10000,150000,450000,850000),dig.lab=7))%>%na.omit()
anaemiafplate=anaemiafplate%>%relocate(time_cat,time)
anaemiafplate.tbl <- anaemiafplate %>% group_by(time_cat, anaemia, plate_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafplate.tbl<-anaemiafplate.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafplate.tbl$anaemia[anaemiafplate.tbl$anaemia == 0] <- "No"
anaemiafplate.tbl$anaemia[anaemiafplate.tbl$anaemia == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(anaemiafplate.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiaplate=anaemiafplate.tbl%>%select("time_cat", "anaemia", "plate_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiaplate %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiaplate) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(plate_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
anaemiafsercre=heartfaildata%>%select(time,DEATH_EVENT,anaemia,serum_creatinine)
anaemiafsercre=anaemiafsercre%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafsercre=anaemiafsercre%>%mutate(sercre_cat=cut(serum_creatinine,breaks=c(0.5,1.3,2,9.5),dig.lab=7))%>%na.omit()
anaemiafsercre=anaemiafsercre%>%relocate(time_cat,time)
anaemiafsercre.tbl <- anaemiafsercre %>% group_by(time_cat, anaemia, sercre_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafsercre.tbl<-anaemiafsercre.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafsercre.tbl$anaemia[anaemiafsercre.tbl$anaemia == 0] <- "No"
anaemiafsercre.tbl$anaemia[anaemiafsercre.tbl$anaemia == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(anaemiafsercre.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiasercre=anaemiafsercre.tbl%>%select("time_cat", "anaemia", "sercre_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiasercre %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiasercre) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(sercre_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```


```{r}
anaemiafsersod=heartfaildata%>%select(time,DEATH_EVENT,anaemia,serum_sodium)
anaemiafsersod=anaemiafsersod%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafsersod=anaemiafsersod%>%mutate(sersod_cat=cut(serum_sodium,breaks=c(110,135,145,150),dig.lab=7))%>%na.omit()
anaemiafsersod=anaemiafsersod%>%relocate(time_cat,time)
anaemiafsersod.tbl <- anaemiafsersod %>% group_by(time_cat, anaemia, sersod_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafsersod.tbl<-anaemiafsersod.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafsersod.tbl$anaemia[anaemiafsersod.tbl$anaemia == 0] <- "No"
anaemiafsersod.tbl$anaemia[anaemiafsersod.tbl$anaemia == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(anaemiafsersod.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiasersod=anaemiafsersod.tbl%>%select("time_cat", "anaemia", "sersod_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiasersod %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiasersod) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(sersod_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```


Diabetes is yes (1) or no (0) to the having it.

```{r}
diabetesf=heartfaildata%>%select(time,DEATH_EVENT,diabetes,age)
diabetesf=diabetesf%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
diabetesf=diabetesf%>%mutate(age_cat=cut(age,breaks=c(40,50,60,70,80,90,95)))%>%na.omit()
diabetesf=diabetesf%>%relocate(time_cat,time)
diabetesf.tbl <- diabetesf %>% group_by(time_cat, diabetes, age_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
diabetesf.tbl<-diabetesf.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
diabetesf.tbl$diabetes[diabetesf.tbl$diabetes == 0] <- "No"
diabetesf.tbl$diabetes[diabetesf.tbl$diabetes == 1] <- "Yes" 

```

```{r,include=FALSE}
stargazer(diabetesf.tbl, summary = F, rownames = F)
```

```{r}
Tablediabetes1 = diabetesf.tbl %>% select("time_cat", "diabetes", "age_cat", 
                                "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tablediabetes1 %>% print(n = Inf)

```

```{r}
ggplot(data = Tablediabetes1) + geom_bar(aes(x = diabetes, y = DeathProb ,
                                     fill = factor(age_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```



```{r}
diabetesfcreatphos=heartfaildata%>%select(time,DEATH_EVENT,diabetes,creatinine_phosphokinase)
diabetesfcreatphos=diabetesfcreatphos%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
diabetesfcreatphos=diabetesfcreatphos%>%mutate(crepho_cat=cut(creatinine_phosphokinase,breaks=c(10,120,500,1000,8000),dig.lab=5))%>%na.omit()
diabetesfcreatphos=diabetesfcreatphos%>%relocate(time_cat,time)
diabetesfcreatphos.tbl <- diabetesfcreatphos %>% group_by(time_cat, diabetes, crepho_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
diabetesfcreatphos.tbl<-diabetesfcreatphos.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
diabetesfcreatphos.tbl$diabetes[diabetesfcreatphos.tbl$diabetes == 0] <- "No"
diabetesfcreatphos.tbl$diabetes[diabetesfcreatphos.tbl$diabetes == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(diabetesfcreatphos.tbl, summary = F, rownames = F)
```

```{r}
Tablediabetescrepho=diabetesfcreatphos.tbl%>%select("time_cat", "diabetes", "crepho_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tablediabetescrepho %>% print(n = Inf)


```

```{r}
ggplot(data = Tablediabetescrepho) + geom_bar(aes(x = diabetes, y = DeathProb ,
                                     fill = factor(crepho_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
diabetesfejectfrac=heartfaildata%>%select(time,DEATH_EVENT,diabetes,ejection_fraction)
diabetesfejectfrac=diabetesfejectfrac%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
diabetesfejectfrac=diabetesfejectfrac%>%mutate(ejectfrac_cat=cut(ejection_fraction,breaks=c(14,35,40,55,80),dig.lab=5))%>%na.omit()
diabetesfejectfrac=diabetesfejectfrac%>%relocate(time_cat,time)
diabetesfejectfrac.tbl <- diabetesfejectfrac %>% group_by(time_cat, diabetes, ejectfrac_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
diabetesfejectfrac.tbl<-diabetesfejectfrac.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
diabetesfejectfrac.tbl$diabetes[diabetesfejectfrac.tbl$diabetes == 0] <- "No"
diabetesfejectfrac.tbl$diabetes[diabetesfejectfrac.tbl$diabetes == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(diabetesfejectfrac.tbl, summary = F, rownames = F)
```

```{r}
Tablediabetesejefra=diabetesfejectfrac.tbl%>%select("time_cat", "diabetes", "ejectfrac_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tablediabetesejefra %>% print(n = Inf)


```

```{r}
ggplot(data = Tablediabetesejefra) + geom_bar(aes(x = diabetes, y = DeathProb ,
                                     fill = factor(ejectfrac_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
diabetesfplate=heartfaildata%>%select(time,DEATH_EVENT,diabetes,platelets)
diabetesfplate=diabetesfplate%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
diabetesfplate=diabetesfplate%>%mutate(plate_cat=cut(platelets,breaks=c(10000,150000,450000,850000),dig.lab=7))%>%na.omit()
diabetesfplate=diabetesfplate%>%relocate(time_cat,time)
diabetesfplate.tbl <- diabetesfplate %>% group_by(time_cat, diabetes, plate_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
diabetesfplate.tbl<-diabetesfplate.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
diabetesfplate.tbl$diabetes[diabetesfplate.tbl$diabetes == 0] <- "No"
diabetesfplate.tbl$diabetes[diabetesfplate.tbl$diabetes == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(diabetesfplate.tbl, summary = F, rownames = F)
```

```{r}
Tablediabetesplate=diabetesfplate.tbl%>%select("time_cat", "diabetes", "plate_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tablediabetesplate %>% print(n = Inf)


```

```{r}
ggplot(data = Tablediabetesplate) + geom_bar(aes(x = diabetes, y = DeathProb ,
                                     fill = factor(plate_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
diabetesfsercre=heartfaildata%>%select(time,DEATH_EVENT,diabetes,serum_creatinine)
diabetesfsercre=diabetesfsercre%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
diabetesfsercre=diabetesfsercre%>%mutate(sercre_cat=cut(serum_creatinine,breaks=c(0.5,1.3,2,9.5),dig.lab=7))%>%na.omit()
diabetesfsercre=diabetesfsercre%>%relocate(time_cat,time)
diabetesfsercre.tbl <- diabetesfsercre %>% group_by(time_cat, diabetes, sercre_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
diabetesfsercre.tbl<-diabetesfsercre.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
diabetesfsercre.tbl$diabetes[diabetesfsercre.tbl$diabetes == 0] <- "No"
diabetesfsercre.tbl$diabetes[diabetesfsercre.tbl$diabetes == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(diabetesfsercre.tbl, summary = F, rownames = F)
```

```{r}
Tablediabetessercre=diabetesfsercre.tbl%>%select("time_cat", "diabetes", "sercre_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tablediabetessercre %>% print(n = Inf)


```

```{r}
ggplot(data = Tablediabetessercre) + geom_bar(aes(x = diabetes, y = DeathProb ,
                                     fill = factor(sercre_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```


```{r}
diabetesfsersod=heartfaildata%>%select(time,DEATH_EVENT,diabetes,serum_sodium)
diabetesfsersod=diabetesfsersod%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
diabetesfsersod=diabetesfsersod%>%mutate(sersod_cat=cut(serum_sodium,breaks=c(110,135,145,150),dig.lab=7))%>%na.omit()
diabetesfsersod=diabetesfsersod%>%relocate(time_cat,time)
diabetesfsersod.tbl <- diabetesfsersod %>% group_by(time_cat, diabetes, sersod_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
diabetesfsersod.tbl<-diabetesfsersod.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
diabetesfsersod.tbl$diabetes[diabetesfsersod.tbl$diabetes == 0] <- "No"
diabetesfsersod.tbl$diabetes[diabetesfsersod.tbl$diabetes == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(diabetesfsersod.tbl, summary = F, rownames = F)
```

```{r}
Tablediabetessersod=diabetesfsersod.tbl%>%select("time_cat", "diabetes", "sersod_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tablediabetessersod %>% print(n = Inf)


```

```{r}
ggplot(data = Tablediabetessersod) + geom_bar(aes(x = diabetes, y = DeathProb ,
                                     fill = factor(sersod_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```


HBP is yes (1) or no (0) to the following question: If the patient has hypertension?

```{r}
HBPf=heartfaildata%>%select(time,DEATH_EVENT,high_blood_pressure,age)
HBPf=HBPf%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
HBPf=HBPf%>%mutate(age_cat=cut(age,breaks=c(40,50,60,70,80,90,95)))%>%na.omit()
HBPf=HBPf%>%relocate(time_cat,time)
HBPf.tbl <- HBPf %>% group_by(time_cat, high_blood_pressure, age_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
HBPf.tbl<-HBPf.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
HBPf.tbl$high_blood_pressure[HBPf.tbl$high_blood_pressure == 0] <- "No"
HBPf.tbl$high_blood_pressure[HBPf.tbl$high_blood_pressure == 1] <- "Yes"

```

```{r,include=FALSE}
stargazer(HBPf.tbl, summary = F, rownames = F)
```

```{r}
TableHBP1 = HBPf.tbl %>% select("time_cat", "high_blood_pressure", "age_cat", 
                                "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
TableHBP1 %>% print(n = Inf)

```

```{r}
ggplot(data = TableHBP1) + geom_bar(aes(x = high_blood_pressure, y = DeathProb ,
                                     fill = factor(age_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```



```{r}
HBPfcreatphos=heartfaildata%>%select(time,DEATH_EVENT,high_blood_pressure,creatinine_phosphokinase)
HBPfcreatphos=HBPfcreatphos%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
HBPfcreatphos=HBPfcreatphos%>%mutate(crepho_cat=cut(creatinine_phosphokinase,breaks=c(10,120,500,1000,8000),dig.lab=5))%>%na.omit()
HBPfcreatphos=HBPfcreatphos%>%relocate(time_cat,time)
HBPfcreatphos.tbl <- HBPfcreatphos %>% group_by(time_cat, high_blood_pressure, crepho_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
HBPfcreatphos.tbl<-HBPfcreatphos.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
HBPfcreatphos.tbl$high_blood_pressure[HBPfcreatphos.tbl$high_blood_pressure == 0] <- "No"
HBPfcreatphos.tbl$high_blood_pressure[HBPfcreatphos.tbl$high_blood_pressure == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(HBPfcreatphos.tbl, summary = F, rownames = F)
```

```{r}
TableHBPcrepho=HBPfcreatphos.tbl%>%select("time_cat", "high_blood_pressure", "crepho_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
TableHBPcrepho %>% print(n = Inf)


```

```{r}
ggplot(data = TableHBPcrepho) + geom_bar(aes(x = high_blood_pressure, y = DeathProb ,
                                     fill = factor(crepho_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
HBPfejectfrac=heartfaildata%>%select(time,DEATH_EVENT,high_blood_pressure,ejection_fraction)
HBPfejectfrac=HBPfejectfrac%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
HBPfejectfrac=HBPfejectfrac%>%mutate(ejectfrac_cat=cut(ejection_fraction,breaks=c(14,35,40,55,80),dig.lab=5))%>%na.omit()
HBPfejectfrac=HBPfejectfrac%>%relocate(time_cat,time)
HBPfejectfrac.tbl <- HBPfejectfrac %>% group_by(time_cat, high_blood_pressure, ejectfrac_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
HBPfejectfrac.tbl<-HBPfejectfrac.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
HBPfejectfrac.tbl$high_blood_pressure[HBPfejectfrac.tbl$high_blood_pressure == 0] <- "No"
HBPfejectfrac.tbl$high_blood_pressure[HBPfejectfrac.tbl$high_blood_pressure == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(HBPfejectfrac.tbl, summary = F, rownames = F)
```

```{r}
TableHBPejefra=HBPfejectfrac.tbl%>%select("time_cat", "high_blood_pressure", "ejectfrac_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
TableHBPejefra %>% print(n = Inf)


```

```{r}
ggplot(data = TableHBPejefra) + geom_bar(aes(x = high_blood_pressure, y = DeathProb ,
                                     fill = factor(ejectfrac_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
HBPfplate=heartfaildata%>%select(time,DEATH_EVENT,high_blood_pressure,platelets)
HBPfplate=HBPfplate%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
HBPfplate=HBPfplate%>%mutate(plate_cat=cut(platelets,breaks=c(10000,150000,450000,850000),dig.lab=7))%>%na.omit()
HBPfplate=HBPfplate%>%relocate(time_cat,time)
HBPfplate.tbl <- HBPfplate %>% group_by(time_cat, high_blood_pressure, plate_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
HBPfplate.tbl<-HBPfplate.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
HBPfplate.tbl$high_blood_pressure[HBPfplate.tbl$high_blood_pressure == 0] <- "No"
HBPfplate.tbl$high_blood_pressure[HBPfplate.tbl$high_blood_pressure == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(HBPfplate.tbl, summary = F, rownames = F)
```

```{r}
TableHBPplate=HBPfplate.tbl%>%select("time_cat", "high_blood_pressure", "plate_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
TableHBPplate %>% print(n = Inf)


```

```{r}
ggplot(data = TableHBPplate) + geom_bar(aes(x = high_blood_pressure, y = DeathProb ,
                                     fill = factor(plate_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
HBPfsercre=heartfaildata%>%select(time,DEATH_EVENT,high_blood_pressure,serum_creatinine)
HBPfsercre=HBPfsercre%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
HBPfsercre=HBPfsercre%>%mutate(sercre_cat=cut(serum_creatinine,breaks=c(0.5,1.3,2,9.5),dig.lab=7))%>%na.omit()
HBPfsercre=HBPfsercre%>%relocate(time_cat,time)
HBPfsercre.tbl <- HBPfsercre %>% group_by(time_cat, high_blood_pressure, sercre_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
HBPfsercre.tbl<-HBPfsercre.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
HBPfsercre.tbl$high_blood_pressure[HBPfsercre.tbl$high_blood_pressure == 0] <- "No"
HBPfsercre.tbl$high_blood_pressure[HBPfsercre.tbl$high_blood_pressure == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(HBPfsercre.tbl, summary = F, rownames = F)
```

```{r}
TableHBPsercre=HBPfsercre.tbl%>%select("time_cat", "high_blood_pressure", "sercre_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
TableHBPsercre %>% print(n = Inf)


```

```{r}
ggplot(data = TableHBPsercre) + geom_bar(aes(x = high_blood_pressure, y = DeathProb ,
                                     fill = factor(sercre_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```


```{r}
HBPfsersod=heartfaildata%>%select(time,DEATH_EVENT,high_blood_pressure,serum_sodium)
HBPfsersod=HBPfsersod%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
HBPfsersod=HBPfsersod%>%mutate(sersod_cat=cut(serum_sodium,breaks=c(110,135,145,150),dig.lab=7))%>%na.omit()
HBPfsersod=HBPfsersod%>%relocate(time_cat,time)
HBPfsersod.tbl <- HBPfsersod %>% group_by(time_cat, high_blood_pressure, sersod_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
HBPfsersod.tbl<-HBPfsersod.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
HBPfsersod.tbl$high_blood_pressure[HBPfsersod.tbl$high_blood_pressure == 0] <- "No"
HBPfsersod.tbl$high_blood_pressure[HBPfsersod.tbl$high_blood_pressure == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(HBPfsersod.tbl, summary = F, rownames = F)
```

```{r}
TableHBPsersod=HBPfsersod.tbl%>%select("time_cat", "high_blood_pressure", "sersod_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
TableHBPsersod %>% print(n = Inf)


```

```{r}
ggplot(data = TableHBPsersod) + geom_bar(aes(x = high_blood_pressure, y = DeathProb ,
                                     fill = factor(sersod_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```


Smoking is yes (1) or no (0) to if the patient smokes?

```{r}
anaemiaf=heartfaildata%>%select(time,DEATH_EVENT,anaemia,age)
anaemiaf=anaemiaf%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiaf=anaemiaf%>%mutate(age_cat=cut(age,breaks=c(40,50,60,70,80,90,95)))%>%na.omit()
anaemiaf=anaemiaf%>%relocate(time_cat,time)
anaemiaf.tbl <- anaemiaf %>% group_by(time_cat, anaemia, age_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiaf.tbl<-anaemiaf.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiaf.tbl$anaemia[anaemiaf.tbl$anaemia == 0] <- "No"
anaemiaf.tbl$anaemia[anaemiaf.tbl$anaemia == 1] <- "Yes"

```

```{r,include=FALSE}
stargazer(anaemiaf.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemia1 = anaemiaf.tbl %>% select("time_cat", "anaemia", "age_cat", 
                                "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemia1 %>% print(n = Inf)

```

```{r}
ggplot(data = Tableanaemia1) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(age_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```



```{r}
anaemiafcreatphos=heartfaildata%>%select(time,DEATH_EVENT,anaemia,creatinine_phosphokinase)
anaemiafcreatphos=anaemiafcreatphos%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafcreatphos=anaemiafcreatphos%>%mutate(crepho_cat=cut(creatinine_phosphokinase,breaks=c(10,120,500,1000,8000),dig.lab=5))%>%na.omit()
anaemiafcreatphos=anaemiafcreatphos%>%relocate(time_cat,time)
anaemiafcreatphos.tbl <- anaemiafcreatphos %>% group_by(time_cat, anaemia, crepho_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafcreatphos.tbl<-anaemiafcreatphos.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafcreatphos.tbl$anaemia[anaemiafcreatphos.tbl$anaemia == 0] <- "No"
anaemiafcreatphos.tbl$anaemia[anaemiafcreatphos.tbl$anaemia == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(anaemiafcreatphos.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiacrepho=anaemiafcreatphos.tbl%>%select("time_cat", "anaemia", "crepho_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiacrepho %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiacrepho) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(crepho_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
anaemiafejectfrac=heartfaildata%>%select(time,DEATH_EVENT,anaemia,ejection_fraction)
anaemiafejectfrac=anaemiafejectfrac%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafejectfrac=anaemiafejectfrac%>%mutate(ejectfrac_cat=cut(ejection_fraction,breaks=c(14,35,40,55,80),dig.lab=5))%>%na.omit()
anaemiafejectfrac=anaemiafejectfrac%>%relocate(time_cat,time)
anaemiafejectfrac.tbl <- anaemiafejectfrac %>% group_by(time_cat, anaemia, ejectfrac_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafejectfrac.tbl<-anaemiafejectfrac.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafejectfrac.tbl$anaemia[anaemiafejectfrac.tbl$anaemia == 0] <- "No"
anaemiafejectfrac.tbl$anaemia[anaemiafejectfrac.tbl$anaemia == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(anaemiafejectfrac.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiaejefra=anaemiafejectfrac.tbl%>%select("time_cat", "anaemia", "ejectfrac_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiaejefra %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiaejefra) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(ejectfrac_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
anaemiafplate=heartfaildata%>%select(time,DEATH_EVENT,anaemia,platelets)
anaemiafplate=anaemiafplate%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafplate=anaemiafplate%>%mutate(plate_cat=cut(platelets,breaks=c(10000,150000,450000,850000),dig.lab=7))%>%na.omit()
anaemiafplate=anaemiafplate%>%relocate(time_cat,time)
anaemiafplate.tbl <- anaemiafplate %>% group_by(time_cat, anaemia, plate_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafplate.tbl<-anaemiafplate.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafplate.tbl$anaemia[anaemiafplate.tbl$anaemia == 0] <- "No"
anaemiafplate.tbl$anaemia[anaemiafplate.tbl$anaemia == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(anaemiafplate.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiaplate=anaemiafplate.tbl%>%select("time_cat", "anaemia", "plate_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiaplate %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiaplate) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(plate_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```

```{r}
anaemiafsercre=heartfaildata%>%select(time,DEATH_EVENT,anaemia,serum_creatinine)
anaemiafsercre=anaemiafsercre%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafsercre=anaemiafsercre%>%mutate(sercre_cat=cut(serum_creatinine,breaks=c(0.5,1.3,2,9.5),dig.lab=7))%>%na.omit()
anaemiafsercre=anaemiafsercre%>%relocate(time_cat,time)
anaemiafsercre.tbl <- anaemiafsercre %>% group_by(time_cat, anaemia, sercre_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafsercre.tbl<-anaemiafsercre.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafsercre.tbl$anaemia[anaemiafsercre.tbl$anaemia == 0] <- "No"
anaemiafsercre.tbl$anaemia[anaemiafsercre.tbl$anaemia == 1] <- "Yes"
```

```{r,include=FALSE}
stargazer(anaemiafsercre.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiasercre=anaemiafsercre.tbl%>%select("time_cat", "anaemia", "sercre_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiasercre %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiasercre) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(sercre_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```


```{r}
anaemiafsersod=heartfaildata%>%select(time,DEATH_EVENT,anaemia,serum_sodium)
anaemiafsersod=anaemiafsersod%>%mutate(time_cat=cut(time,breaks=c(0,30,60,100,285)))%>%na.omit()
anaemiafsersod=anaemiafsersod%>%mutate(sersod_cat=cut(serum_sodium,breaks=c(110,135,145,150),dig.lab=7))%>%na.omit()
anaemiafsersod=anaemiafsersod%>%relocate(time_cat,time)
anaemiafsersod.tbl <- anaemiafsersod %>% group_by(time_cat, anaemia, sersod_cat, DEATH_EVENT, .drop = F) %>%
  tally() %>% spread(DEATH_EVENT, n, replace_na(0)) %>%
  mutate(Total = `0` + `1`)
anaemiafsersod.tbl<-anaemiafsersod.tbl%>%mutate(DeathProb=`1`/`Total`)%>%replace_na(list(Total=0,DeathProb=0))
anaemiafsersod.tbl$anaemia[anaemiafsersod.tbl$anaemia == 0] <- "female"
anaemiafsersod.tbl$anaemia[anaemiafsersod.tbl$anaemia == 1] <- "male"
```

```{r,include=FALSE}
stargazer(anaemiafsersod.tbl, summary = F, rownames = F)
```

```{r}
Tableanaemiasersod=anaemiafsersod.tbl%>%select("time_cat", "anaemia", "sersod_cat", 
                              "DEATH_EVENT_No" = "0", "DEATH_EVENT_Yes" = "1", "Total","DeathProb")
Tableanaemiasersod %>% print(n = Inf)


```

```{r}
ggplot(data = Tableanaemiasersod) + geom_bar(aes(x = anaemia, y = DeathProb ,
                                     fill = factor(sersod_cat)),
                                 position = "dodge", stat = "identity") +
  ylab("Probability of Death") +
  facet_wrap(~ time_cat)
```



